import streamlit
#streamlit.title('Hello, Harish here..')
#streamlit.header('List of My Hobbies:')
#streamlit.text('Playing Cricket')
#streamlit.text('Hiking')
streamlit.header('My Parents New Healthy Diner')
streamlit.header('Breakfast Menu')
streamlit.text('Omega 3 & Blueberry Oatmeal')
streamlit.text('Kale, Spinach & Rocket Smoothie')
streamlit.text('Hard-Boiled Free-Range Egg')
